import ejercicio1.py
@startuml

class Nodo {
    pregunta
    superheroe
    izquierda
    derecha
}

class ArbolDecision {
    raiz
    obtener_superheroe()
}

Nodo -- Nodo
ArbolDecision -- Nodo

ArbolDecision ..> obtener_superheroe()

@enduml

